server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jayzhoou/springcloud.git
          searchPaths: config
          username: jayzhoou
          password: 09708030g
      label: master
eureka:
 client:
  service-url:
    defaultZone: http://localhost:8761/eureka/

